CREATE SCHEMA ZDRES;
CREATE TABLE ZDRES.CAR
(
 ID SERIAL,
  MAKE TEXT NOT NULL DEFAULT '',
  MODEL TEXT NOT NULL DEFAULT '',
   LAT DOUBLE NOT NULL DEFAULT 0,
  LONG DOUBLE NOT NULL DEFAULT 0,
  RESERVATION_SEQ INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE ZDRES.RESERVATION (
  ID SERIAL,
  USER_ID INTEGER NOT NULL DEFAULT 0,
  CAR_ID INTEGER NOT NULL REFERENCES ZDRES.CAR(ID),
  START_T TIMESTAMP NOT NULL,
  STOP_T TIMESTAMP NOT NULL
);
