CREATE SCHEMA ZDRES;
CREATE TABLE ZDRES.CAR
(
 ID SERIAL,
  MAKE TEXT NOT NULL DEFAULT '',
  MODEL TEXT NOT NULL DEFAULT '',
   LAT DOUBLE NOT NULL DEFAULT 0,
  LONG DOUBLE NOT NULL DEFAULT 0,
  RESERVATION_SEQ INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE ZDRES.RESERVATION (
  ID SERIAL,
  USER_ID INTEGER NOT NULL DEFAULT 0,
  CAR_ID INTEGER NOT NULL REFERENCES ZDRES.CAR(ID),
  START_T TIMESTAMP NOT NULL,
  STOP_T TIMESTAMP NOT NULL
);

CREATE OR REPLACE FUNCTION distance(lat1 FLOAT, lon1 FLOAT, lat2 FLOAT, lon2 FLOAT) RETURNS FLOAT AS $$
DECLARE
  x float = 69.1 * (lat2 - lat1);
  y float = 69.1 * (lon2 - lon1) * cos(lat1 / 57.3);
BEGIN
  RETURN sqrt(x * x + y * y);
END
$$ LANGUAGE plpgsql;
